export const FETCH_QUIZES_START = "FETCH_QUIZES_START";
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";

export const QUIZ_SET_STATE = "QUIZ_SET_STATE";
export const FINISH_QUIZ = "FINISH_QUIZ";
export const QUIZ_NEXT_QUESTION = "QUIZ_NEXT_QUESTION";
export const QUIZ_RETRY = "QUIZ_RETRY";

export const CREATE_QUIZ_QUESTION = "CREATE_QUIZ_QUESTION";
export const RESET_QUIZ_QUESTION = "RESET_QUIZ_QUESTION";

export const FETCH_LESSONS_START = "FETCH_LESSONS_START";
export const FETCH_LESSONS_SUCCESS = "FETCH_LESSONS_SUCCESS";
export const FETCH_LESSONS_ERROR = "FETCH_LESSONS_ERROR";
export const FETCH_LESSON_SUCCESS = "FETCH_LESSON_SUCCESS";

export const CREATE_LESSON = "CREATE_LESSON";
export const RESET_LESSON = "RESET_LESSON";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
